# Generated by Django 5.2 on 2025-04-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpecializationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('numberProject', models.CharField(max_length=10)),
                ('icon', models.ImageField(upload_to='icon/')),
            ],
            options={
                'verbose_name': 'تخصص ها',
                'verbose_name_plural': 'تخصص ها',
            },
        ),
        migrations.RenameModel(
            old_name='SocialLinks',
            new_name='SocialLinksModel',
        ),
    ]
