# Generated by Django 5.2 on 2025-04-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_userspecializationmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home_title', 'عنوان صفحه اصلی'), ('home_subtitle', 'زیرعنوان صفحه اصلی'), ('about_title', 'عنوان درباره ما'), ('contact_title', 'عنوان تماس با ما'), ('footer_copyright', 'کپی\u200cرایت فوتر')], max_length=100, unique=True)),
                ('value', models.TextField()),
                ('language', models.CharField(default='fa', max_length=10)),
            ],
        ),
    ]
