# Generated by Django 5.2 on 2025-04-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_sitetext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('type_experiences', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'تجربه ها',
                'verbose_name_plural': 'تجربه ها',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'دسته بندی نمودار ',
                'verbose_name_plural': 'دسته بندی نمودار ',
            },
        ),
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'نمونه کار ها',
                'verbose_name_plural': 'نمونه کار ها',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'خبرنامه',
                'verbose_name_plural': 'خبرنامه',
            },
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='key',
            field=models.CharField(choices=[('email', 'ایمیل'), ('phone_number', 'شماره تلفن'), ('address', 'آدرس'), ('footer_title', 'عنوان فوتر'), ('contact_small_title', 'عنوان کوچک تماس باما'), ('contact_big_title', 'عنوان بزرگ تماس باما'), ('توضیحات تماس باما', 'Contact Description'), ('portfolio_title', 'عنوان نمونه کار'), ('portfolio_description', 'توضیحات نمونه کار'), ('experiences_title', 'عنوان تجربیات')], max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='KnowledgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('percent', models.IntegerField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.knowledgecategorymodel')),
            ],
            options={
                'verbose_name': 'نمودار دانش',
                'verbose_name_plural': 'نمودار دانش',
            },
        ),
    ]
