# Generated by Django 5.2 on 2025-04-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_contactmessage_experiencesmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'درباره من',
                'verbose_name_plural': 'درباره من',
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('logo', 'لوگو'), ('hero', 'عکس هیرو سکشن'), ('about', 'عکس بخش درباره من'), ('experiences', 'عکس بخش تجربیات')], max_length=100, unique=True)),
                ('value', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='LogoModel',
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='key',
            field=models.CharField(choices=[('hello_text', 'متن سلام'), ('name', 'نام'), ('title_job', 'عنوان کاری'), ('about_description_hero', 'توضیحات درباره من بخش هیرو سکشن'), ('email', 'ایمیل'), ('phone_number', 'شماره تلفن'), ('address', 'آدرس'), ('footer_title', 'عنوان فوتر'), ('contact_small_title', 'عنوان کوچک تماس باما'), ('contact_big_title', 'عنوان بزرگ تماس باما'), ('توضیحات تماس باما', 'Contact Description'), ('portfolio_title', 'عنوان نمونه کار'), ('portfolio_description', 'توضیحات نمونه کار'), ('experiences_title', 'عنوان تجربیات'), ('about_small_title', 'عنوان کوچک بخش درباره ما'), ('about_big_title', 'عنوان بزرگ بخش درباره ما'), ('about_description', 'توضیحات بخش درباره ما')], max_length=100, unique=True),
        ),
    ]
