# Generated by Django 5.2 on 2025-04-28 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_aboutmodel_siteimage_delete_logomodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='siteimage',
            options={'verbose_name': 'عکس های سایت', 'verbose_name_plural': 'عکس های سایت'},
        ),
        migrations.AlterModelOptions(
            name='sitetext',
            options={'verbose_name': 'متن های سایت', 'verbose_name_plural': 'متن های سایت'},
        ),
    ]
