# Generated by Django 5.2 on 2025-05-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_alter_contactmessage_options_alter_siteimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgemodel',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
