# Generated by Django 5.2 on 2025-05-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_alter_knowledgemodel_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallinksmodel',
            old_name='github',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='sociallinksmodel',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='sociallinksmodel',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='sociallinksmodel',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='sociallinksmodel',
            name='icon',
            field=models.ImageField(default=1, upload_to='socialImage/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sociallinksmodel',
            name='social_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
