# Generated by Django 5.2 on 2025-05-22 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_rename_github_sociallinksmodel_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='core_app.knowledgecategorymodel'),
        ),
        migrations.AlterField(
            model_name='sitetext',
            name='key',
            field=models.CharField(choices=[('hello_text', 'متن سلام'), ('name', 'نام'), ('title_job', 'عنوان کاری'), ('about_description_hero', 'توضیحات درباره من بخش هیرو سکشن'), ('email', 'ایمیل'), ('phone_number', 'شماره تلفن'), ('address', 'آدرس'), ('footer_title', 'عنوان فوتر'), ('contact_small_title', 'عنوان کوچک تماس باما'), ('contact_big_title', 'عنوان بزرگ تماس باما'), ('contact_description', 'توضیحات تماس باما'), ('portfolio_title', 'عنوان نمونه کار'), ('portfolio_description', 'توضیحات نمونه کار'), ('experiences_title', 'عنوان تجربیات'), ('about_small_title', 'عنوان کوچک بخش درباره ما'), ('about_big_title', 'عنوان بزرگ بخش درباره ما'), ('about_description', 'توضیحات بخش درباره ما')], max_length=100, unique=True),
        ),
    ]
