# Generated by Django 5.2 on 2025-05-24 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_alter_knowledgemodel_category_alter_sitetext_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspecializationmodel',
            name='icon',
            field=models.FileField(upload_to='icon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
