# Generated by Django 5.1.7 on 2025-05-29 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_alter_userspecializationmodel_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceYearsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'سال های تجربه ',
                'verbose_name_plural': 'سال های تجربه',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatisticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('numberProject', models.CharField(max_length=10)),
                ('icon', models.ImageField(upload_to='icon/')),
            ],
            options={
                'verbose_name': 'آمار پروژه ها ',
                'verbose_name_plural': 'آمار پروژه ها',
            },
        ),
        migrations.AlterField(
            model_name='sociallinksmodel',
            name='icon',
            field=models.FileField(upload_to='socialImage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
