# Generated by Django 5.1.7 on 2025-05-29 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_experienceyearsmodel_projectstatisticsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstatisticsmodel',
            name='icon',
            field=models.FileField(upload_to='icon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
